"""Admin operations for Odoo users."""

from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path

from .docker import detect_compose_command
from .ui import console, error_console


class AdminError(Exception):
    """Raised when an admin operation fails."""


# Python script executed by click-odoo inside the container.
# Placeholders are filled with .format() before the file is written.
# Double braces {{ }} become literal { } after formatting.
_RESET_SCRIPT = """\
# Generated by dbodoo admin reset — do not edit manually.
import logging
_logger = logging.getLogger(__name__)

Users = env["res.users"].with_context(active_test=False)
user = Users.browse({user_id})

if not user.exists():
    raise SystemExit("User id={user_id} not found in database {dbname!r}.")

# Activate user and set login
user.write({{"active": True, "login": {login!r}}})

# Reset password
user._change_password({password!r})

# Disable TOTP / 2FA
{totp_line}

env.cr.commit()
_logger.info("dbodoo admin reset complete: user id=%s, login=%s", user.id, user.login)
"""

_TOTP_DISABLE = (
    'env.cr.execute("UPDATE res_users SET totp_secret = NULL WHERE id = %s", [{user_id}])'
)
_TOTP_SKIP = "# 2FA not modified (--keep-2fa passed)"


def reset_admin(
    project_path: Path,
    dbname: str,
    *,
    login: str = "admin",
    password: str = "admin",
    user_id: int = 2,
    disable_2fa: bool = True,
) -> None:
    """Reset an Odoo admin user inside the Docker Compose ``odoo`` service.

    Runs a ``click-odoo`` script inside the container that:

    * Activates the user (``active = True``)
    * Sets the login
    * Resets the password via :meth:`res.users._change_password`
    * Optionally NULLs ``totp_secret`` to disable TOTP 2FA

    The script is written to a temp file, bind-mounted read-only into the
    container, and executed via ``click-odoo -d {dbname}``, mirroring the
    same pattern used by :func:`~dbodoo.docker.restore_database`.

    Args:
        project_path: Root of the Doodba project (where ``docker-compose.yml`` lives).
        dbname: Name of the local Odoo database to connect to.
        login: New login value (default: ``"admin"``).
        password: New plain-text password (default: ``"admin"``).
        user_id: Database id of the user to reset (default: ``2``).
        disable_2fa: When ``True``, NULL the ``totp_secret`` column (default: ``True``).

    Raises:
        DockerError: if Docker Compose is not available.
        AdminError: if ``click-odoo`` exits with a non-zero return code.
    """
    compose_cmd = detect_compose_command()  # raises DockerError if not found

    totp_line = (
        _TOTP_DISABLE.format(user_id=user_id) if disable_2fa else _TOTP_SKIP
    )

    script_content = _RESET_SCRIPT.format(
        user_id=user_id,
        dbname=dbname,
        login=login,
        password=password,
        totp_line=totp_line,
    )

    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix="_dbodoo_reset_admin.py",
        delete=False,
        encoding="utf-8",
    ) as tmp:
        tmp.write(script_content)
        tmp_path = Path(tmp.name)

    mount_target = "/mnt/dbodoo_reset_admin.py"

    cmd = [
        *compose_cmd,
        "run",
        "--rm",
        "-v",
        f"{tmp_path.resolve()}:{mount_target}:ro",
        "odoo",
        "click-odoo",
        "-d",
        dbname,
        mount_target,
    ]

    console.print(
        f"Resetting admin user "
        f"(db=[cyan]{dbname}[/cyan], id=[cyan]{user_id}[/cyan], "
        f"login=[cyan]{login!r}[/cyan])…"
    )

    try:
        result = subprocess.run(cmd, cwd=project_path)
    finally:
        tmp_path.unlink(missing_ok=True)

    if result.returncode != 0:
        msg = (
            f"click-odoo exited with code {result.returncode}. "
            "Check the Docker Compose output above for details.\n"
            "Make sure the database exists and the odoo service is configured."
        )
        raise AdminError(msg)

    console.print("[bold green]✓[/bold green] Admin reset complete.")
    console.print(f"  Login:    [cyan]{login}[/cyan]")
    console.print(f"  Password: [cyan]{password}[/cyan]")
    if disable_2fa:
        console.print("  2FA:      [cyan]disabled[/cyan]")
    console.print("  Status:   [cyan]active[/cyan]")
