"""Neutralize outgoing mail configuration in local Odoo databases."""

from __future__ import annotations

from pathlib import Path

from dbodoo.ui import console

from .utils import run_odoo_shell_script


# Python executed inside the Odoo shell via stdin.
# env / self are provided by the shell; no imports needed for ORM access.
#
# Why SQL instead of ORM:
#   Odoo 18 added a constraint in ir.mail_server.write() that raises UserError
#   when trying to archive a server still referenced by email templates.
#   Direct SQL bypasses that validator while remaining safe for local neutralization.
_MAIL_SCRIPT = """\
# Generated by dbodoo neutralize mail — do not edit manually.
import logging
_logger = logging.getLogger(__name__)

# Count active servers first
env.cr.execute("SELECT COUNT(*) FROM ir_mail_server WHERE active = TRUE")
count = env.cr.fetchone()[0]

if count == 0:
    print("No active outgoing mail servers found — nothing to disable.")
else:
    # Direct SQL bypasses the ORM constraint that refuses to archive servers
    # still referenced by email templates (introduced in Odoo 18).
    env.cr.execute("UPDATE ir_mail_server SET active = FALSE WHERE active = TRUE")
    print(f"Found {count} mail server(s).")
    print("All outgoing mail servers disabled successfully.")

env.cr.commit()
_logger.info("dbodoo neutralize mail: %d server(s) disabled", count)
"""


def neutralize_mail(project_path: Path, dbname: str) -> None:
    """Disable all active outgoing mail servers in a local Odoo database.

    Sets ``active = False`` on every ``ir.mail_server`` record, preventing
    Odoo from sending any outgoing email.

    Args:
        project_path: Root of the Doodba project (where ``docker-compose.yml`` lives).
        dbname: Name of the local database to neutralize.

    Raises:
        DockerError: if Docker Compose is not available.
        NeutralizeError: if the operation fails inside the container.
    """
    console.print(f"Neutralizing outgoing mail (db=[cyan]{dbname}[/cyan])…")
    run_odoo_shell_script(project_path, dbname, _MAIL_SCRIPT)
    console.print("[bold green]✓[/bold green] Mail neutralization complete.")
